// Nios2.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module Nios2 (
		input  wire        clk_clk,           //        clk.clk
		output wire        clk_sdram_clk,     //  clk_sdram.clk
		output wire [6:0]  hex0_export,       //       hex0.export
		output wire [6:0]  hex1_export,       //       hex1.export
		output wire [6:0]  hex2_export,       //       hex2.export
		output wire [6:0]  hex3_export,       //       hex3.export
		output wire [7:0]  pio_led_export,    //    pio_led.export
		input  wire [7:0]  pio_sw_export,     //     pio_sw.export
		output wire        pll_locked_export, // pll_locked.export
		input  wire        reset_reset_n,     //      reset.reset_n
		output wire [11:0] sdram_wire_addr,   // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,     //           .ba
		output wire        sdram_wire_cas_n,  //           .cas_n
		output wire        sdram_wire_cke,    //           .cke
		output wire        sdram_wire_cs_n,   //           .cs_n
		inout  wire [15:0] sdram_wire_dq,     //           .dq
		output wire [1:0]  sdram_wire_dqm,    //           .dqm
		output wire        sdram_wire_ras_n,  //           .ras_n
		output wire        sdram_wire_we_n    //           .we_n
	);

	wire         pll_outclk0_clk;                                       // PLL:outclk_0 -> [SDRAM:clk, mm_interconnect_0:PLL_outclk0_clk, rst_controller_002:clk]
	wire  [31:0] cpu_data_master_readdata;                              // mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	wire         cpu_data_master_waitrequest;                           // mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	wire         cpu_data_master_debugaccess;                           // CPU:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	wire  [24:0] cpu_data_master_address;                               // CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	wire   [3:0] cpu_data_master_byteenable;                            // CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	wire         cpu_data_master_read;                                  // CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	wire         cpu_data_master_write;                                 // CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	wire  [31:0] cpu_data_master_writedata;                             // CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	wire  [31:0] cpu_instruction_master_readdata;                       // mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	wire         cpu_instruction_master_waitrequest;                    // mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	wire  [24:0] cpu_instruction_master_address;                        // CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	wire         cpu_instruction_master_read;                           // CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	wire         mm_interconnect_0_juart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:JUART_avalon_jtag_slave_chipselect -> JUART:av_chipselect
	wire  [31:0] mm_interconnect_0_juart_avalon_jtag_slave_readdata;    // JUART:av_readdata -> mm_interconnect_0:JUART_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_juart_avalon_jtag_slave_waitrequest; // JUART:av_waitrequest -> mm_interconnect_0:JUART_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_juart_avalon_jtag_slave_address;     // mm_interconnect_0:JUART_avalon_jtag_slave_address -> JUART:av_address
	wire         mm_interconnect_0_juart_avalon_jtag_slave_read;        // mm_interconnect_0:JUART_avalon_jtag_slave_read -> JUART:av_read_n
	wire         mm_interconnect_0_juart_avalon_jtag_slave_write;       // mm_interconnect_0:JUART_avalon_jtag_slave_write -> JUART:av_write_n
	wire  [31:0] mm_interconnect_0_juart_avalon_jtag_slave_writedata;   // mm_interconnect_0:JUART_avalon_jtag_slave_writedata -> JUART:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata; // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;  // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_cpu_debug_mem_slave_readdata;        // CPU:debug_mem_slave_readdata -> mm_interconnect_0:CPU_debug_mem_slave_readdata
	wire         mm_interconnect_0_cpu_debug_mem_slave_waitrequest;     // CPU:debug_mem_slave_waitrequest -> mm_interconnect_0:CPU_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_cpu_debug_mem_slave_debugaccess;     // mm_interconnect_0:CPU_debug_mem_slave_debugaccess -> CPU:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_cpu_debug_mem_slave_address;         // mm_interconnect_0:CPU_debug_mem_slave_address -> CPU:debug_mem_slave_address
	wire         mm_interconnect_0_cpu_debug_mem_slave_read;            // mm_interconnect_0:CPU_debug_mem_slave_read -> CPU:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_cpu_debug_mem_slave_byteenable;      // mm_interconnect_0:CPU_debug_mem_slave_byteenable -> CPU:debug_mem_slave_byteenable
	wire         mm_interconnect_0_cpu_debug_mem_slave_write;           // mm_interconnect_0:CPU_debug_mem_slave_write -> CPU:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_cpu_debug_mem_slave_writedata;       // mm_interconnect_0:CPU_debug_mem_slave_writedata -> CPU:debug_mem_slave_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                   // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                     // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [14:0] mm_interconnect_0_ram_s1_address;                      // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                   // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                        // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                    // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                        // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire         mm_interconnect_0_pio_led_s1_chipselect;               // mm_interconnect_0:PIO_LED_s1_chipselect -> PIO_LED:chipselect
	wire  [31:0] mm_interconnect_0_pio_led_s1_readdata;                 // PIO_LED:readdata -> mm_interconnect_0:PIO_LED_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_led_s1_address;                  // mm_interconnect_0:PIO_LED_s1_address -> PIO_LED:address
	wire         mm_interconnect_0_pio_led_s1_write;                    // mm_interconnect_0:PIO_LED_s1_write -> PIO_LED:write_n
	wire  [31:0] mm_interconnect_0_pio_led_s1_writedata;                // mm_interconnect_0:PIO_LED_s1_writedata -> PIO_LED:writedata
	wire  [31:0] mm_interconnect_0_pio_sw_s1_readdata;                  // PIO_SW:readdata -> mm_interconnect_0:PIO_SW_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_sw_s1_address;                   // mm_interconnect_0:PIO_SW_s1_address -> PIO_SW:address
	wire         mm_interconnect_0_sdram_s1_chipselect;                 // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                   // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [21:0] mm_interconnect_0_sdram_s1_address;                    // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                       // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                 // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;              // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                      // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                  // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire         mm_interconnect_0_seg7_0_s1_chipselect;                // mm_interconnect_0:SEG7_0_s1_chipselect -> SEG7_0:chipselect
	wire  [31:0] mm_interconnect_0_seg7_0_s1_readdata;                  // SEG7_0:readdata -> mm_interconnect_0:SEG7_0_s1_readdata
	wire   [1:0] mm_interconnect_0_seg7_0_s1_address;                   // mm_interconnect_0:SEG7_0_s1_address -> SEG7_0:address
	wire         mm_interconnect_0_seg7_0_s1_write;                     // mm_interconnect_0:SEG7_0_s1_write -> SEG7_0:write_n
	wire  [31:0] mm_interconnect_0_seg7_0_s1_writedata;                 // mm_interconnect_0:SEG7_0_s1_writedata -> SEG7_0:writedata
	wire         mm_interconnect_0_seg7_1_s1_chipselect;                // mm_interconnect_0:SEG7_1_s1_chipselect -> SEG7_1:chipselect
	wire  [31:0] mm_interconnect_0_seg7_1_s1_readdata;                  // SEG7_1:readdata -> mm_interconnect_0:SEG7_1_s1_readdata
	wire   [1:0] mm_interconnect_0_seg7_1_s1_address;                   // mm_interconnect_0:SEG7_1_s1_address -> SEG7_1:address
	wire         mm_interconnect_0_seg7_1_s1_write;                     // mm_interconnect_0:SEG7_1_s1_write -> SEG7_1:write_n
	wire  [31:0] mm_interconnect_0_seg7_1_s1_writedata;                 // mm_interconnect_0:SEG7_1_s1_writedata -> SEG7_1:writedata
	wire         mm_interconnect_0_seg7_2_s1_chipselect;                // mm_interconnect_0:SEG7_2_s1_chipselect -> SEG7_2:chipselect
	wire  [31:0] mm_interconnect_0_seg7_2_s1_readdata;                  // SEG7_2:readdata -> mm_interconnect_0:SEG7_2_s1_readdata
	wire   [1:0] mm_interconnect_0_seg7_2_s1_address;                   // mm_interconnect_0:SEG7_2_s1_address -> SEG7_2:address
	wire         mm_interconnect_0_seg7_2_s1_write;                     // mm_interconnect_0:SEG7_2_s1_write -> SEG7_2:write_n
	wire  [31:0] mm_interconnect_0_seg7_2_s1_writedata;                 // mm_interconnect_0:SEG7_2_s1_writedata -> SEG7_2:writedata
	wire         mm_interconnect_0_seg7_3_s1_chipselect;                // mm_interconnect_0:SEG7_3_s1_chipselect -> SEG7_3:chipselect
	wire  [31:0] mm_interconnect_0_seg7_3_s1_readdata;                  // SEG7_3:readdata -> mm_interconnect_0:SEG7_3_s1_readdata
	wire   [1:0] mm_interconnect_0_seg7_3_s1_address;                   // mm_interconnect_0:SEG7_3_s1_address -> SEG7_3:address
	wire         mm_interconnect_0_seg7_3_s1_write;                     // mm_interconnect_0:SEG7_3_s1_write -> SEG7_3:write_n
	wire  [31:0] mm_interconnect_0_seg7_3_s1_writedata;                 // mm_interconnect_0:SEG7_3_s1_writedata -> SEG7_3:writedata
	wire         mm_interconnect_0_sys_clk_timer_s1_chipselect;         // mm_interconnect_0:sys_clk_timer_s1_chipselect -> sys_clk_timer:chipselect
	wire  [15:0] mm_interconnect_0_sys_clk_timer_s1_readdata;           // sys_clk_timer:readdata -> mm_interconnect_0:sys_clk_timer_s1_readdata
	wire   [2:0] mm_interconnect_0_sys_clk_timer_s1_address;            // mm_interconnect_0:sys_clk_timer_s1_address -> sys_clk_timer:address
	wire         mm_interconnect_0_sys_clk_timer_s1_write;              // mm_interconnect_0:sys_clk_timer_s1_write -> sys_clk_timer:write_n
	wire  [15:0] mm_interconnect_0_sys_clk_timer_s1_writedata;          // mm_interconnect_0:sys_clk_timer_s1_writedata -> sys_clk_timer:writedata
	wire         irq_mapper_receiver0_irq;                              // JUART:av_irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                              // sys_clk_timer:irq -> irq_mapper:receiver1_irq
	wire  [31:0] cpu_irq_irq;                                           // irq_mapper:sender_irq -> CPU:irq
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [CPU:reset_n, JUART:rst_n, PIO_SW:reset_n, RAM:reset, SEG7_0:reset_n, SEG7_1:reset_n, SEG7_2:reset_n, SEG7_3:reset_n, irq_mapper:reset, mm_interconnect_0:CPU_reset_reset_bridge_in_reset_reset, rst_translator:in_reset, sys_clk_timer:reset_n, sysid_qsys_0:reset_n]
	wire         rst_controller_reset_out_reset_req;                    // rst_controller:reset_req -> [CPU:reset_req, RAM:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                    // rst_controller_001:reset_out -> [PIO_LED:reset_n, mm_interconnect_0:PIO_LED_reset_reset_bridge_in_reset_reset]
	wire         cpu_debug_reset_request_reset;                         // CPU:debug_reset_request -> rst_controller_001:reset_in1
	wire         rst_controller_002_reset_out_reset;                    // rst_controller_002:reset_out -> [SDRAM:reset_n, mm_interconnect_0:SDRAM_reset_reset_bridge_in_reset_reset]

	Nios2_CPU cpu (
		.clk                                 (clk_clk),                                           //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                   //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                //                          .reset_req
		.d_address                           (cpu_data_master_address),                           //               data_master.address
		.d_byteenable                        (cpu_data_master_byteenable),                        //                          .byteenable
		.d_read                              (cpu_data_master_read),                              //                          .read
		.d_readdata                          (cpu_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (cpu_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (cpu_data_master_write),                             //                          .write
		.d_writedata                         (cpu_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (cpu_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (cpu_instruction_master_address),                    //        instruction_master.address
		.i_read                              (cpu_instruction_master_read),                       //                          .read
		.i_readdata                          (cpu_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (cpu_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (cpu_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (cpu_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_cpu_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_cpu_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_cpu_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_cpu_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_cpu_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_cpu_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_cpu_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_cpu_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                   // custom_instruction_master.readra
	);

	Nios2_JUART juart (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_juart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_juart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_juart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_juart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_juart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_juart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_juart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	Nios2_PIO_LED pio_led (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),     //               reset.reset_n
		.address    (mm_interconnect_0_pio_led_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_led_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_led_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_led_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_led_s1_readdata),   //                    .readdata
		.out_port   (pio_led_export)                           // external_connection.export
	);

	Nios2_PIO_SW pio_sw (
		.clk      (clk_clk),                              //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address  (mm_interconnect_0_pio_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_sw_s1_readdata), //                    .readdata
		.in_port  (pio_sw_export)                         // external_connection.export
	);

	Nios2_PLL pll (
		.refclk   (clk_clk),           //  refclk.clk
		.rst      (~reset_reset_n),    //   reset.reset
		.outclk_0 (pll_outclk0_clk),   // outclk0.clk
		.outclk_1 (clk_sdram_clk),     // outclk1.clk
		.locked   (pll_locked_export)  //  locked.export
	);

	Nios2_RAM ram (
		.clk        (clk_clk),                             //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze     (1'b0)                                 // (terminated)
	);

	Nios2_SDRAM sdram (
		.clk            (pll_outclk0_clk),                          //   clk.clk
		.reset_n        (~rst_controller_002_reset_out_reset),      // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	Nios2_SEG7_0 seg7_0 (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_seg7_0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seg7_0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seg7_0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seg7_0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seg7_0_s1_readdata),   //                    .readdata
		.out_port   (hex0_export)                             // external_connection.export
	);

	Nios2_SEG7_0 seg7_1 (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_seg7_1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seg7_1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seg7_1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seg7_1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seg7_1_s1_readdata),   //                    .readdata
		.out_port   (hex1_export)                             // external_connection.export
	);

	Nios2_SEG7_0 seg7_2 (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_seg7_2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seg7_2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seg7_2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seg7_2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seg7_2_s1_readdata),   //                    .readdata
		.out_port   (hex2_export)                             // external_connection.export
	);

	Nios2_SEG7_0 seg7_3 (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_seg7_3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seg7_3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seg7_3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seg7_3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seg7_3_s1_readdata),   //                    .readdata
		.out_port   (hex3_export)                             // external_connection.export
	);

	Nios2_sys_clk_timer sys_clk_timer (
		.clk        (clk_clk),                                       //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               // reset.reset_n
		.address    (mm_interconnect_0_sys_clk_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_sys_clk_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_sys_clk_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_sys_clk_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_sys_clk_timer_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver1_irq)                       //   irq.irq
	);

	Nios2_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                       //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	Nios2_mm_interconnect_0 mm_interconnect_0 (
		.CLK_clk_clk                               (clk_clk),                                               //                             CLK_clk.clk
		.PLL_outclk0_clk                           (pll_outclk0_clk),                                       //                         PLL_outclk0.clk
		.CPU_reset_reset_bridge_in_reset_reset     (rst_controller_reset_out_reset),                        //     CPU_reset_reset_bridge_in_reset.reset
		.PIO_LED_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                    // PIO_LED_reset_reset_bridge_in_reset.reset
		.SDRAM_reset_reset_bridge_in_reset_reset   (rst_controller_002_reset_out_reset),                    //   SDRAM_reset_reset_bridge_in_reset.reset
		.CPU_data_master_address                   (cpu_data_master_address),                               //                     CPU_data_master.address
		.CPU_data_master_waitrequest               (cpu_data_master_waitrequest),                           //                                    .waitrequest
		.CPU_data_master_byteenable                (cpu_data_master_byteenable),                            //                                    .byteenable
		.CPU_data_master_read                      (cpu_data_master_read),                                  //                                    .read
		.CPU_data_master_readdata                  (cpu_data_master_readdata),                              //                                    .readdata
		.CPU_data_master_write                     (cpu_data_master_write),                                 //                                    .write
		.CPU_data_master_writedata                 (cpu_data_master_writedata),                             //                                    .writedata
		.CPU_data_master_debugaccess               (cpu_data_master_debugaccess),                           //                                    .debugaccess
		.CPU_instruction_master_address            (cpu_instruction_master_address),                        //              CPU_instruction_master.address
		.CPU_instruction_master_waitrequest        (cpu_instruction_master_waitrequest),                    //                                    .waitrequest
		.CPU_instruction_master_read               (cpu_instruction_master_read),                           //                                    .read
		.CPU_instruction_master_readdata           (cpu_instruction_master_readdata),                       //                                    .readdata
		.CPU_debug_mem_slave_address               (mm_interconnect_0_cpu_debug_mem_slave_address),         //                 CPU_debug_mem_slave.address
		.CPU_debug_mem_slave_write                 (mm_interconnect_0_cpu_debug_mem_slave_write),           //                                    .write
		.CPU_debug_mem_slave_read                  (mm_interconnect_0_cpu_debug_mem_slave_read),            //                                    .read
		.CPU_debug_mem_slave_readdata              (mm_interconnect_0_cpu_debug_mem_slave_readdata),        //                                    .readdata
		.CPU_debug_mem_slave_writedata             (mm_interconnect_0_cpu_debug_mem_slave_writedata),       //                                    .writedata
		.CPU_debug_mem_slave_byteenable            (mm_interconnect_0_cpu_debug_mem_slave_byteenable),      //                                    .byteenable
		.CPU_debug_mem_slave_waitrequest           (mm_interconnect_0_cpu_debug_mem_slave_waitrequest),     //                                    .waitrequest
		.CPU_debug_mem_slave_debugaccess           (mm_interconnect_0_cpu_debug_mem_slave_debugaccess),     //                                    .debugaccess
		.JUART_avalon_jtag_slave_address           (mm_interconnect_0_juart_avalon_jtag_slave_address),     //             JUART_avalon_jtag_slave.address
		.JUART_avalon_jtag_slave_write             (mm_interconnect_0_juart_avalon_jtag_slave_write),       //                                    .write
		.JUART_avalon_jtag_slave_read              (mm_interconnect_0_juart_avalon_jtag_slave_read),        //                                    .read
		.JUART_avalon_jtag_slave_readdata          (mm_interconnect_0_juart_avalon_jtag_slave_readdata),    //                                    .readdata
		.JUART_avalon_jtag_slave_writedata         (mm_interconnect_0_juart_avalon_jtag_slave_writedata),   //                                    .writedata
		.JUART_avalon_jtag_slave_waitrequest       (mm_interconnect_0_juart_avalon_jtag_slave_waitrequest), //                                    .waitrequest
		.JUART_avalon_jtag_slave_chipselect        (mm_interconnect_0_juart_avalon_jtag_slave_chipselect),  //                                    .chipselect
		.PIO_LED_s1_address                        (mm_interconnect_0_pio_led_s1_address),                  //                          PIO_LED_s1.address
		.PIO_LED_s1_write                          (mm_interconnect_0_pio_led_s1_write),                    //                                    .write
		.PIO_LED_s1_readdata                       (mm_interconnect_0_pio_led_s1_readdata),                 //                                    .readdata
		.PIO_LED_s1_writedata                      (mm_interconnect_0_pio_led_s1_writedata),                //                                    .writedata
		.PIO_LED_s1_chipselect                     (mm_interconnect_0_pio_led_s1_chipselect),               //                                    .chipselect
		.PIO_SW_s1_address                         (mm_interconnect_0_pio_sw_s1_address),                   //                           PIO_SW_s1.address
		.PIO_SW_s1_readdata                        (mm_interconnect_0_pio_sw_s1_readdata),                  //                                    .readdata
		.RAM_s1_address                            (mm_interconnect_0_ram_s1_address),                      //                              RAM_s1.address
		.RAM_s1_write                              (mm_interconnect_0_ram_s1_write),                        //                                    .write
		.RAM_s1_readdata                           (mm_interconnect_0_ram_s1_readdata),                     //                                    .readdata
		.RAM_s1_writedata                          (mm_interconnect_0_ram_s1_writedata),                    //                                    .writedata
		.RAM_s1_byteenable                         (mm_interconnect_0_ram_s1_byteenable),                   //                                    .byteenable
		.RAM_s1_chipselect                         (mm_interconnect_0_ram_s1_chipselect),                   //                                    .chipselect
		.RAM_s1_clken                              (mm_interconnect_0_ram_s1_clken),                        //                                    .clken
		.SDRAM_s1_address                          (mm_interconnect_0_sdram_s1_address),                    //                            SDRAM_s1.address
		.SDRAM_s1_write                            (mm_interconnect_0_sdram_s1_write),                      //                                    .write
		.SDRAM_s1_read                             (mm_interconnect_0_sdram_s1_read),                       //                                    .read
		.SDRAM_s1_readdata                         (mm_interconnect_0_sdram_s1_readdata),                   //                                    .readdata
		.SDRAM_s1_writedata                        (mm_interconnect_0_sdram_s1_writedata),                  //                                    .writedata
		.SDRAM_s1_byteenable                       (mm_interconnect_0_sdram_s1_byteenable),                 //                                    .byteenable
		.SDRAM_s1_readdatavalid                    (mm_interconnect_0_sdram_s1_readdatavalid),              //                                    .readdatavalid
		.SDRAM_s1_waitrequest                      (mm_interconnect_0_sdram_s1_waitrequest),                //                                    .waitrequest
		.SDRAM_s1_chipselect                       (mm_interconnect_0_sdram_s1_chipselect),                 //                                    .chipselect
		.SEG7_0_s1_address                         (mm_interconnect_0_seg7_0_s1_address),                   //                           SEG7_0_s1.address
		.SEG7_0_s1_write                           (mm_interconnect_0_seg7_0_s1_write),                     //                                    .write
		.SEG7_0_s1_readdata                        (mm_interconnect_0_seg7_0_s1_readdata),                  //                                    .readdata
		.SEG7_0_s1_writedata                       (mm_interconnect_0_seg7_0_s1_writedata),                 //                                    .writedata
		.SEG7_0_s1_chipselect                      (mm_interconnect_0_seg7_0_s1_chipselect),                //                                    .chipselect
		.SEG7_1_s1_address                         (mm_interconnect_0_seg7_1_s1_address),                   //                           SEG7_1_s1.address
		.SEG7_1_s1_write                           (mm_interconnect_0_seg7_1_s1_write),                     //                                    .write
		.SEG7_1_s1_readdata                        (mm_interconnect_0_seg7_1_s1_readdata),                  //                                    .readdata
		.SEG7_1_s1_writedata                       (mm_interconnect_0_seg7_1_s1_writedata),                 //                                    .writedata
		.SEG7_1_s1_chipselect                      (mm_interconnect_0_seg7_1_s1_chipselect),                //                                    .chipselect
		.SEG7_2_s1_address                         (mm_interconnect_0_seg7_2_s1_address),                   //                           SEG7_2_s1.address
		.SEG7_2_s1_write                           (mm_interconnect_0_seg7_2_s1_write),                     //                                    .write
		.SEG7_2_s1_readdata                        (mm_interconnect_0_seg7_2_s1_readdata),                  //                                    .readdata
		.SEG7_2_s1_writedata                       (mm_interconnect_0_seg7_2_s1_writedata),                 //                                    .writedata
		.SEG7_2_s1_chipselect                      (mm_interconnect_0_seg7_2_s1_chipselect),                //                                    .chipselect
		.SEG7_3_s1_address                         (mm_interconnect_0_seg7_3_s1_address),                   //                           SEG7_3_s1.address
		.SEG7_3_s1_write                           (mm_interconnect_0_seg7_3_s1_write),                     //                                    .write
		.SEG7_3_s1_readdata                        (mm_interconnect_0_seg7_3_s1_readdata),                  //                                    .readdata
		.SEG7_3_s1_writedata                       (mm_interconnect_0_seg7_3_s1_writedata),                 //                                    .writedata
		.SEG7_3_s1_chipselect                      (mm_interconnect_0_seg7_3_s1_chipselect),                //                                    .chipselect
		.sys_clk_timer_s1_address                  (mm_interconnect_0_sys_clk_timer_s1_address),            //                    sys_clk_timer_s1.address
		.sys_clk_timer_s1_write                    (mm_interconnect_0_sys_clk_timer_s1_write),              //                                    .write
		.sys_clk_timer_s1_readdata                 (mm_interconnect_0_sys_clk_timer_s1_readdata),           //                                    .readdata
		.sys_clk_timer_s1_writedata                (mm_interconnect_0_sys_clk_timer_s1_writedata),          //                                    .writedata
		.sys_clk_timer_s1_chipselect               (mm_interconnect_0_sys_clk_timer_s1_chipselect),         //                                    .chipselect
		.sysid_qsys_0_control_slave_address        (mm_interconnect_0_sysid_qsys_0_control_slave_address),  //          sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata       (mm_interconnect_0_sysid_qsys_0_control_slave_readdata)  //                                    .readdata
	);

	Nios2_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.sender_irq    (cpu_irq_irq)                     //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_debug_reset_request_reset),      // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (pll_outclk0_clk),                    //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
